#!/usr/bin/env bash
# weekly-review.sh — Bryan's weekly review and summary generator
# Usage: bash scripts/weekly-review.sh

set -euo pipefail

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RESET='\033[0m'

section() { echo -e "\n${CYAN}══ $1 ══${RESET}"; }
ok()      { echo -e "  ${GREEN}✔${RESET}  $1"; }
warn()    { echo -e "  ${YELLOW}⚠${RESET}  $1"; }

TODAY=$(date '+%Y-%m-%d')
WEEK_START=$(date -d "last monday" '+%Y-%m-%d' 2>/dev/null \
             || date -v-mon '+%Y-%m-%d' 2>/dev/null \
             || echo "this-week")
WEEK_END=$TODAY

SUMMARY_DIR="logs/weekly"
SUMMARY_FILE="${SUMMARY_DIR}/week-of-${WEEK_START}.md"
mkdir -p "$SUMMARY_DIR"

echo -e "${CYAN}"
printf '╔══════════════════════════════════════════╗\n'
printf "║  Bryan's Weekly Review — %-16s  ║\n" "$TODAY"
printf '╚══════════════════════════════════════════╝'"${RESET}"$'\n'

# ── 1. Collect this week's daily logs ────────────────────────────────────────
section "Collecting Daily Logs (${WEEK_START} → ${WEEK_END})"
LOG_DIR="logs/daily"
LOGS_FOUND=0
ACCOMPLISHMENTS=""
INCOMPLETE=""

if [ -d "$LOG_DIR" ]; then
  # Dates are YYYY-MM-DD so lexicographic string comparison is equivalent to
  # chronological order — this is safe for ISO 8601 format.
  for LOG in "$LOG_DIR"/*.md; do
    [ -f "$LOG" ] || continue
    LOG_DATE=$(basename "$LOG" .md)
    if [[ "$LOG_DATE" > "$WEEK_START" || "$LOG_DATE" == "$WEEK_START" ]] \
       && [[ "$LOG_DATE" < "$WEEK_END"  || "$LOG_DATE" == "$WEEK_END"  ]]; then
      LOGS_FOUND=$((LOGS_FOUND + 1))
      # Collect accomplishments
      ACCS=$(awk '/^## Accomplishments/,/^##/' "$LOG" \
             | grep -E '^\s*-\s+[^[]' | sed "s/^/  [${LOG_DATE}] /" || true)
      [ -n "$ACCS" ] && ACCOMPLISHMENTS+="$ACCS"$'\n'
      # Collect incomplete items
      INC=$(grep -E '^\s*-\s*\[ \]' "$LOG" | sed "s/^/  [${LOG_DATE}] /" || true)
      [ -n "$INC" ] && INCOMPLETE+="$INC"$'\n'
    fi
  done
fi

ok "Found ${LOGS_FOUND} daily log(s) for this week"

# ── 2. Git activity summary ───────────────────────────────────────────────────
section "Git Activity This Week"
GIT_LOG=""
if [ -d ".git" ]; then
  GIT_LOG=$(git log --oneline --since="${WEEK_START}" --until="${WEEK_END} 23:59" \
                    --format="  - %s (%ad)" --date=short 2>/dev/null || true)
  if [ -n "$GIT_LOG" ]; then
    echo "$GIT_LOG"
  else
    warn "No commits found for this week"
  fi
fi

# ── 3. Write summary file ─────────────────────────────────────────────────────
section "Generating Summary: ${SUMMARY_FILE}"

cat > "$SUMMARY_FILE" <<SUMMARY
# Weekly Summary — Week of ${WEEK_START}

**Period:** ${WEEK_START} → ${WEEK_END}
**Generated:** $(date '+%Y-%m-%d %H:%M %Z')

---

## Accomplishments

${ACCOMPLISHMENTS:-"  _(fill in from daily logs)_"}

## Incomplete / Carry-Forward Items

${INCOMPLETE:-"  _(none — great week!)_"}

## Git Commits This Week

${GIT_LOG:-"  _(no commits recorded)_"}

---

## Next Week's Top Priorities

1. [Add priority]
2. [Add priority]
3. [Add priority]

## Notes & Reflections

- [Add notes]

---

_Generated by \`scripts/weekly-review.sh\`_
SUMMARY

ok "Summary written to ${SUMMARY_FILE}"
echo "  📝  Open ${SUMMARY_FILE} to review and fill in next week's priorities."

# ── 4. Commit the summary ─────────────────────────────────────────────────────
if [ -d ".git" ]; then
  git add "$SUMMARY_FILE" 2>/dev/null || true
  if ! git diff --cached --quiet 2>/dev/null; then
    git commit -m "docs(log): weekly summary ${WEEK_START}"
    git push 2>/dev/null || warn "Push failed — check remote connection"
    ok "Weekly summary committed"
  fi
fi

echo -e "\n${GREEN}✔  Weekly review complete — great work this week!${RESET}\n"
